/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int compute_dynamics_G(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int compute_dynamics_G_alloc_mem(void);
int compute_dynamics_G_init_mem(int mem);
void compute_dynamics_G_free_mem(int mem);
int compute_dynamics_G_checkout(void);
void compute_dynamics_G_release(int mem);
void compute_dynamics_G_incref(void);
void compute_dynamics_G_decref(void);
casadi_int compute_dynamics_G_n_in(void);
casadi_int compute_dynamics_G_n_out(void);
casadi_real compute_dynamics_G_default_in(casadi_int i);
const char* compute_dynamics_G_name_in(casadi_int i);
const char* compute_dynamics_G_name_out(casadi_int i);
const casadi_int* compute_dynamics_G_sparsity_in(casadi_int i);
const casadi_int* compute_dynamics_G_sparsity_out(casadi_int i);
int compute_dynamics_G_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int compute_dynamics_G_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define compute_dynamics_G_SZ_ARG 1
#define compute_dynamics_G_SZ_RES 1
#define compute_dynamics_G_SZ_IW 0
#define compute_dynamics_G_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
