/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_dynamics_G_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[10] = 
  {6, 1, 0, 6, 0, 1, 2, 3,
  4, 5};

/* compute_dynamics_G:(q[6])->(G[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45;
  a00=arg[0]? arg[0][1] : 0;
  a01=cos(a00);
  a02=-1.6737575084144495e-02;
  a03=3.8950577550375902e+00;
  a04=9.8100000000000005e+00;
  a00=sin(a00);
  a05=(a04*a00);
  a06=(a03*a05);
  a07=(a02*a06);
  a08=arg[0]? arg[0][2] : 0;
  a09=sin(a08);
  a10=9.9231767079920069e-02;
  a11=1.5516196544988501e+00;
  a12=(a09*a05);
  a08=cos(a08);
  a04=(a04*a01);
  a13=(a08*a04);
  a12=(a12+a13);
  a13=(a11*a12);
  a14=(a10*a13);
  a15=arg[0]? arg[0][3] : 0;
  a16=cos(a15);
  a17=-1.0923001102327501e-02;
  a18=1.8819999954752999e+00;
  a19=(a18*a12);
  a20=(a17*a19);
  a21=-7.1266999970153996e-02;
  a15=sin(a15);
  a22=(a09*a04);
  a05=(a08*a05);
  a22=(a22-a05);
  a05=(a15*a22);
  a23=(a18*a05);
  a24=(a21*a23);
  a20=(a20+a24);
  a24=arg[0]? arg[0][4] : 0;
  a25=cos(a24);
  a26=1.1844871373887801e-02;
  a27=1.3462185523491601e+00;
  a28=(a25*a12);
  a24=sin(a24);
  a29=(a16*a22);
  a30=(a24*a29);
  a28=(a28-a30);
  a30=(a27*a28);
  a31=(a26*a30);
  a32=-2.0914200013670600e-02;
  a33=(a27*a05);
  a34=(a32*a33);
  a31=(a31+a34);
  a34=arg[0]? arg[0][5] : 0;
  a35=cos(a34);
  a36=7.9000180089019905e-05;
  a37=6.3399999735158397e-01;
  a28=(a37*a28);
  a38=(a36*a28);
  a39=-4.4852999792347997e-02;
  a34=sin(a34);
  a40=(a25*a29);
  a12=(a24*a12);
  a40=(a40+a12);
  a12=(a34*a40);
  a41=(a35*a05);
  a12=(a12+a41);
  a12=(a37*a12);
  a41=(a39*a12);
  a38=(a38+a41);
  a41=(a35*a38);
  a42=(a35*a40);
  a05=(a34*a05);
  a42=(a42-a05);
  a37=(a37*a42);
  a39=(a39*a37);
  a42=7.2999313560878593e-05;
  a05=(a42*a28);
  a39=(a39-a05);
  a05=(a34*a39);
  a41=(a41-a05);
  a05=1.0349999999999999e-01;
  a43=(a34*a37);
  a44=(a35*a12);
  a43=(a43-a44);
  a44=(a05*a43);
  a41=(a41-a44);
  a31=(a31+a41);
  a41=(a25*a31);
  a44=-1.4130070954595200e-03;
  a45=(a44*a33);
  a27=(a27*a40);
  a26=(a26*a27);
  a45=(a45+a26);
  a42=(a42*a12);
  a36=(a36*a37);
  a42=(a42+a36);
  a45=(a45+a42);
  a36=(a24*a45);
  a41=(a41+a36);
  a36=1.3600000000000001e-01;
  a37=(a35*a37);
  a12=(a34*a12);
  a37=(a37+a12);
  a12=(a27+a37);
  a26=(a24*a12);
  a28=(a30+a28);
  a40=(a25*a28);
  a26=(a26+a40);
  a40=(a36*a26);
  a41=(a41+a40);
  a20=(a20+a41);
  a41=(a16*a20);
  a18=(a18*a29);
  a21=(a21*a18);
  a29=-2.5001138373925199e-05;
  a40=(a29*a19);
  a21=(a21-a40);
  a32=(a32*a27);
  a44=(a44*a30);
  a32=(a32-a44);
  a34=(a34*a38);
  a35=(a35*a39);
  a34=(a34+a35);
  a05=(a05*a37);
  a34=(a34+a05);
  a32=(a32+a34);
  a21=(a21+a32);
  a34=(a15*a21);
  a41=(a41-a34);
  a34=4.0000000000000002e-01;
  a12=(a25*a12);
  a28=(a24*a28);
  a12=(a12-a28);
  a28=(a18+a12);
  a05=(a15*a28);
  a43=(a43-a33);
  a43=(a43-a23);
  a33=(a16*a43);
  a05=(a05+a33);
  a33=(a34*a05);
  a41=(a41-a33);
  a14=(a14+a41);
  a41=(a09*a14);
  a24=(a24*a31);
  a25=(a25*a45);
  a24=(a24-a25);
  a36=(a36*a12);
  a24=(a24-a36);
  a29=(a29*a23);
  a17=(a17*a18);
  a29=(a29+a17);
  a24=(a24-a29);
  a29=-5.0000000000000003e-02;
  a17=(a29*a05);
  a17=(a24+a17);
  a11=(a11*a22);
  a10=(a10*a11);
  a17=(a17-a10);
  a10=(a08*a17);
  a41=(a41+a10);
  a10=5.0000000000000003e-02;
  a22=(a10*a05);
  a41=(a41+a22);
  a07=(a07+a41);
  a01=(a01*a07);
  a03=(a03*a04);
  a02=(a02*a03);
  a14=(a08*a14);
  a17=(a09*a17);
  a14=(a14-a17);
  a05=(a34*a05);
  a14=(a14-a05);
  a02=(a02+a14);
  a00=(a00*a02);
  a01=(a01-a00);
  if (res[0]!=0) res[0][0]=a01;
  a01=-5.9976427873222084e-03;
  a01=(a01*a11);
  a00=-1.0167731118478497e-03;
  a00=(a00*a13);
  a01=(a01-a00);
  a20=(a15*a20);
  a21=(a16*a21);
  a20=(a20+a21);
  a16=(a16*a28);
  a15=(a15*a43);
  a16=(a16-a15);
  a15=(a34*a16);
  a19=(a19+a26);
  a29=(a29*a19);
  a15=(a15-a29);
  a20=(a20+a15);
  a01=(a01+a20);
  a11=(a11+a16);
  a16=(a08*a11);
  a13=(a13+a19);
  a19=(a09*a13);
  a16=(a16-a19);
  a34=(a34*a16);
  a09=(a09*a11);
  a08=(a08*a13);
  a09=(a09+a08);
  a10=(a10*a09);
  a34=(a34-a10);
  a34=(a01+a34);
  a10=-6.9816860425777574e-02;
  a10=(a10*a06);
  a06=1.6930413958959495e-01;
  a06=(a06*a03);
  a10=(a10+a06);
  a34=(a34-a10);
  if (res[0]!=0) res[0][1]=a34;
  a01=(-a01);
  if (res[0]!=0) res[0][2]=a01;
  if (res[0]!=0) res[0][3]=a24;
  a32=(-a32);
  if (res[0]!=0) res[0][4]=a32;
  a42=(-a42);
  if (res[0]!=0) res[0][5]=a42;
  return 0;
}

CASADI_SYMBOL_EXPORT int compute_dynamics_G(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int compute_dynamics_G_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int compute_dynamics_G_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void compute_dynamics_G_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int compute_dynamics_G_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void compute_dynamics_G_release(int mem) {
}

CASADI_SYMBOL_EXPORT void compute_dynamics_G_incref(void) {
}

CASADI_SYMBOL_EXPORT void compute_dynamics_G_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int compute_dynamics_G_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int compute_dynamics_G_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real compute_dynamics_G_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* compute_dynamics_G_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* compute_dynamics_G_name_out(casadi_int i) {
  switch (i) {
    case 0: return "G";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* compute_dynamics_G_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* compute_dynamics_G_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int compute_dynamics_G_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int compute_dynamics_G_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_compute_dynamics_G(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[58];
  casadi_int *iw = 0;
  const casadi_real* arg[1] = {0};
  casadi_real* res[1] = {0};
  if (argc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"compute_dynamics_G\" failed. Too many input arguments (%d, max 1)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"compute_dynamics_G\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s1, w+12);
  --resc;
  res[0] = w+6;
  compute_dynamics_G_incref();
  mem = compute_dynamics_G_checkout();
  i = compute_dynamics_G(arg, res, iw, w+12, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"compute_dynamics_G\" failed.");
  compute_dynamics_G_release(mem);
  compute_dynamics_G_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[19];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_compute_dynamics_G(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "compute_dynamics_G")==0) {
    mex_compute_dynamics_G(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'compute_dynamics_G'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
